sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: manager123
  wechat:
    appid: wx65b92901e41aeb13
    secret: 76f6352aa791dc82779022af839aa3c0